"use client";

import { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import QRGenerator from "@/components/QRGenerator";
import BulkGenerator from "@/components/BulkGenerator";
import PosterGenerator from "@/components/PosterGenerator";
import AdminPanel from "@/components/AdminPanel";
import HistoryPanel from "@/components/HistoryPanel";
import ToastContainer from "@/components/Toast";
import AuthModal from "@/components/AuthModal";
import { useQRHistory } from "@/hooks/useQRHistory";
import { useToast } from "@/hooks/useToast";
import { 
  Palette, 
  Image as ImageIcon, 
  Zap, 
  Download, 
  Wifi, 
  Tag, 
  Sparkles, 
  History, 
  ChevronDown, 
  CheckCircle, 
  Ban, 
  QrCode 
} from "lucide-react";

export type ActiveTab = "generate" | "bulk" | "poster" | "history" | "admin";

// ── SEO Features Section ─────────────────────────────────────────────────────
const FEATURES = [
  {
    icon: <Palette size={28} />,
    title: "Custom Shapes & Colors",
    desc: "Choose from 9 module shapes, 6 corner styles, solid colors or gradients. No other free tool matches this level of design control.",
  },
  {
    icon: <ImageIcon size={28} />,
    title: "Logo & Brand Embedding",
    desc: "Embed your company logo at the center with adjustable size, padding, and corner radius. Error correction ensures your QR stays scannable.",
  },
  {
    icon: <Zap size={28} />,
    title: "Bulk Generate 100 QR Codes",
    desc: "Paste or upload a list of URLs and generate up to 100 QR codes simultaneously. Download all in one click — perfect for campaigns and print runs.",
  },
  {
    icon: <Download size={28} />,
    title: "SVG & High-Res PNG Export",
    desc: "Download pixel-perfect SVG vector files for print or PNG up to 2048×2048px. No watermarks, no hidden fees.",
  },
  {
    icon: <Wifi size={28} />,
    title: "WiFi, vCard & More Formats",
    desc: "Generate QR codes for WiFi networks, contacts (vCard), email, phone numbers, PDF documents, and audio files hosted in the cloud.",
  },
  {
    icon: <Tag size={28} />,
    title: "Frames, Labels & Callouts",
    desc: "Wrap your QR code in 20+ stylized frames like banners, tags, and badges. Add custom text labels like 'Scan Me' above or below.",
  },
  {
    icon: <Sparkles size={28} />,
    title: "AI Poster QR Art",
    desc: "Transform any URL into a scannable art poster using AI-generated backgrounds and split-layout designs. Great for events and marketing.",
  },
  {
    icon: <History size={28} />,
    title: "Scan History & Re-Download",
    desc: "Every QR code you create is saved locally. Browse, copy, or re-download up to 50 previously generated codes without any account.",
  },
];

const HOW_TO_STEPS = [
  {
    step: "01",
    title: "Enter Your Content",
    desc: "Type a URL, text, WiFi password, or contact info — or upload a PDF/audio file to auto-host it and generate a shareable QR link.",
  },
  {
    step: "02",
    title: "Customize the Design",
    desc: "Pick module shapes, corner styles, colors, gradients, logo, background image, frame, and labels. Preview updates live as you design.",
  },
  {
    step: "03",
    title: "Download & Share",
    desc: "Download your QR code as a high-resolution PNG (up to 2048px) or scalable SVG vector — print-ready and watermark-free.",
  },
];

const FAQ_ITEMS = [
  {
    q: "Is HappyQR completely free to use?",
    a: "Yes! HappyQR is free with generous daily limits — no credit card or signup required. Create a free account for extended daily limits or go Pro for unlimited QR generation and premium features.",
  },
  {
    q: "Do the QR codes ever expire?",
    a: "Never. QR codes generated by HappyQR are static — all data is encoded directly into the image pattern. They work forever, as long as a QR scanner can read the image. No server dependency.",
  },
  {
    q: "Can I add my logo to a QR code?",
    a: "Absolutely. In Section 4 (Logo & Background), upload any PNG or JPG logo. Adjust the size, padding, background color, and corner radius. HappyQR automatically uses Error Correction Level H (30% damage recovery) to keep the QR scannable.",
  },
  {
    q: "What is the difference between PNG and SVG download?",
    a: "PNG is a raster image — best for web, social media, and digital sharing. Select up to 2048×2048px for high print quality. SVG is a vector format that scales to any size without losing quality — ideal for professional print materials like banners and merchandise.",
  },
  {
    q: "How do I generate a WiFi QR code?",
    a: "Click the 'WiFi' tab in Section 1 (Content & Formats), enter your network name (SSID), password, and security type (WPA2 / WPA3). The QR code will let anyone connect to your WiFi instantly by scanning — no typing needed.",
  },
  {
    q: "Can I generate QR codes in bulk?",
    a: "Yes! Switch to the 'Bulk Generate' tab. Enter or paste a list of URLs (one per line), select the design style, and click Generate. Up to 100 QR codes are created simultaneously. All codes can be downloaded at once.",
  },
  {
    q: "Do I need to create an account?",
    a: "No account is needed to generate QR codes. Anonymous users can generate up to 5 QR codes per day. Creating a free account raises your daily limit significantly. Pro users get unlimited generation and access to all premium features.",
  },
];

function FAQAccordion() {
  const [openIdx, setOpenIdx] = useState<number | null>(null);
  return (
    <div className="faq-list" role="list">
      {FAQ_ITEMS.map((item, i) => (
        <div
          key={i}
          className={`faq-item ${openIdx === i ? "open" : ""}`}
          role="listitem"
        >
          <button
            className="faq-question"
            aria-expanded={openIdx === i}
            onClick={() => setOpenIdx(openIdx === i ? null : i)}
          >
            <span>{item.q}</span>
            <ChevronDown 
              className={`faq-chevron ${openIdx === i ? "open" : ""}`} 
              aria-hidden="true" 
              size={18}
            />
          </button>
          <div className="faq-answer" aria-hidden={openIdx !== i}>
            <p>{item.a}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

function SEOContentBlock() {
  return (
    <section className="seo-content-block" aria-label="About HappyQR">
      {/* ── Features Grid ───────────────────────────────────── */}
      <div className="seo-section">
        <div className="seo-section-label" style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
          <Sparkles size={11} /> Why HappyQR
        </div>
        <h2 className="seo-heading">
          The Most Powerful Free{" "}
          <span className="highlight">QR Code Generator</span> Online
        </h2>
        <p className="seo-subheading">
          Design professional QR codes with complete customization. Free to use,
          no watermarks, no signup required — just beautiful, scannable QR codes
          that represent your brand.
        </p>
        <div className="features-grid" role="list">
          {FEATURES.map((f, i) => (
            <article key={i} className="feature-card" role="listitem">
              <div className="feature-icon" aria-hidden="true">
                {f.icon}
              </div>
              <h3 className="feature-title">{f.title}</h3>
              <p className="feature-desc">{f.desc}</p>
            </article>
          ))}
        </div>
      </div>

      {/* ── How-To Steps ────────────────────────────────────── */}
      <div className="seo-section seo-section-alt">
        <div className="seo-section-label" style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
          <Sparkles size={11} /> Getting Started
        </div>
        <h2 className="seo-heading">
          Create a Custom QR Code in{" "}
          <span className="highlight">3 Simple Steps</span>
        </h2>
        <p className="seo-subheading">
          No design experience required. Go from idea to a print-ready QR code
          in under 60 seconds.
        </p>
        <div className="steps-timeline" role="list">
          {HOW_TO_STEPS.map((s, i) => (
            <div key={i} className="step-card" role="listitem">
              <div className="step-number" aria-label={`Step ${s.step}`}>
                {s.step}
              </div>
              <div className="step-content">
                <h3 className="step-title">{s.title}</h3>
                <p className="step-desc">{s.desc}</p>
              </div>
              {i < HOW_TO_STEPS.length - 1 && (
                <div className="step-connector" aria-hidden="true" />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* ── FAQ ─────────────────────────────────────────────── */}
      <div className="seo-section">
        <div className="seo-section-label" style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
          <Sparkles size={11} /> FAQs
        </div>
        <h2 className="seo-heading">
          Frequently Asked{" "}
          <span className="highlight">Questions</span>
        </h2>
        <p className="seo-subheading">
          Everything you need to know about generating, downloading and using
          your QR codes.
        </p>
        <FAQAccordion />
      </div>

      {/* ── Footer ──────────────────────────────────────────── */}
      <footer className="site-footer" role="contentinfo">
        <div className="footer-grid">
          <div className="footer-brand">
            <div className="footer-logo">
              <QrCode className="footer-logo-icon" size={22} />
              <span className="footer-logo-text">HappyQR</span>
            </div>
            <p className="footer-tagline">
              Free, beautiful, and powerful QR code generation for individuals
              and businesses worldwide. No watermarks. No expiration.
            </p>
            <div className="footer-badges">
              <span className="footer-badge" style={{ display: "inline-flex", alignItems: "center", gap: "5px" }}>
                <CheckCircle size={12} style={{ color: "var(--accent-green)" }} /> Free Forever
              </span>
              <span className="footer-badge" style={{ display: "inline-flex", alignItems: "center", gap: "5px" }}>
                <Ban size={12} style={{ color: "var(--accent-red)" }} /> No Watermark
              </span>
              <span className="footer-badge" style={{ display: "inline-flex", alignItems: "center", gap: "5px" }}>
                <Zap size={12} style={{ color: "var(--accent-amber)" }} /> Instant Download
              </span>
            </div>
          </div>
          <div className="footer-links-group">
            <h4 className="footer-links-title">QR Code Types</h4>
            <ul className="footer-links">
              <li>URL / Website QR Code</li>
              <li>WiFi QR Code</li>
              <li>vCard / Contact QR Code</li>
              <li>Email QR Code</li>
              <li>Phone Number QR Code</li>
              <li>PDF QR Code</li>
              <li>Audio File QR Code</li>
              <li>Plain Text QR Code</li>
            </ul>
          </div>
          <div className="footer-links-group">
            <h4 className="footer-links-title">Design Features</h4>
            <ul className="footer-links">
              <li>Custom Module Shapes</li>
              <li>Corner & Eye Styles</li>
              <li>Color Gradients</li>
              <li>Logo & Image Embedding</li>
              <li>QR Code Frames & Labels</li>
              <li>Background Wallpapers</li>
              <li>AI Poster QR Art</li>
              <li>Bulk QR Generation</li>
            </ul>
          </div>
          <div className="footer-links-group">
            <h4 className="footer-links-title">Download Formats</h4>
            <ul className="footer-links">
              <li>PNG — 256px (Web)</li>
              <li>PNG — 512px (Standard)</li>
              <li>PNG — 1024px (Print)</li>
              <li>PNG — 2048px (HD Print)</li>
              <li>SVG — Vector (Scalable)</li>
            </ul>
          </div>
        </div>
        <div className="footer-bottom">
          <p className="footer-copy">
            © {new Date().getFullYear()} HappyQR — Free QR Code Generator. All
            rights reserved.
          </p>
          <p className="footer-note">
            Built with ♥ for creators, marketers, and businesses. QR codes
            generated are static and never expire.
          </p>
        </div>
      </footer>
    </section>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────
export default function Home() {
  const [activeTab, setActiveTab] = useState<ActiveTab>("generate");
  const { history, addToHistory, clearHistory, removeFromHistory, totalGenerated } = useQRHistory();
  const { toasts, showToast } = useToast();
  
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [isAuthOpen, setIsAuthOpen] = useState(false);

  useEffect(() => {
    const savedTheme = localStorage.getItem("happyqr_theme") as "dark" | "light" | null;
    if (savedTheme) {
      setTheme(savedTheme);
      document.documentElement.setAttribute("data-theme", savedTheme);
    } else {
      document.documentElement.setAttribute("data-theme", "dark");
    }

    const savedUser = localStorage.getItem("happyqr_user");
    if (savedUser) {
      setUserEmail(savedUser);
    }
  }, []);

  const toggleTheme = () => {
    const nextTheme = theme === "dark" ? "light" : "dark";
    setTheme(nextTheme);
    localStorage.setItem("happyqr_theme", nextTheme);
    document.documentElement.setAttribute("data-theme", nextTheme);
  };

  const handleLoginSuccess = (email: string) => {
    setUserEmail(email);
    localStorage.setItem("happyqr_user", email);
    try {
      const registered = JSON.parse(localStorage.getItem("happyqr_registered_users") || "[]");
      if (!registered.includes(email)) {
        registered.push(email);
        localStorage.setItem("happyqr_registered_users", JSON.stringify(registered));
      }
    } catch (e) {
      /* ignore */
    }
    showToast(`Logged in as ${email}`, "success");
  };

  const handleLogout = () => {
    setUserEmail(null);
    localStorage.removeItem("happyqr_user");
    showToast("Logged out successfully", "info");
  };

  return (
    <>
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        theme={theme}
        toggleTheme={toggleTheme}
        userEmail={userEmail}
        onLoginClick={() => setIsAuthOpen(true)}
        onLogout={handleLogout}
      />
      <main className="main-content">
        <Hero activeTab={activeTab} setActiveTab={setActiveTab} totalGenerated={totalGenerated} />

        {activeTab === "generate" && (
          <QRGenerator
            onGenerate={(entry) => addToHistory(entry)}
            showToast={showToast}
            userEmail={userEmail}
            onLoginClick={() => setIsAuthOpen(true)}
          />
        )}
        {activeTab === "bulk" && (
          <BulkGenerator
            onGenerate={(entries) => entries.forEach(addToHistory)}
            showToast={showToast}
            userEmail={userEmail}
            onLoginClick={() => setIsAuthOpen(true)}
          />
        )}
        {activeTab === "poster" && (
          <PosterGenerator
            showToast={showToast}
            userEmail={userEmail}
            onLoginClick={() => setIsAuthOpen(true)}
          />
        )}
        {activeTab === "history" && (
          <HistoryPanel
            history={history}
            onClear={clearHistory}
            onRemove={removeFromHistory}
            showToast={showToast}
            setActiveTab={setActiveTab}
          />
        )}
        {activeTab === "admin" && (
          <AdminPanel
            showToast={showToast}
            userEmail={userEmail}
          />
        )}

        {/* SEO Content Block — features, how-to, FAQ, footer */}
        <SEOContentBlock />
      </main>
      <ToastContainer toasts={toasts} />
      <AuthModal
        isOpen={isAuthOpen}
        onClose={() => setIsAuthOpen(false)}
        onLoginSuccess={handleLoginSuccess}
      />
    </>
  );
}
